# Generated by Django 5.0.1 on 2024-01-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0002_test_country_test_description_test_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='cast',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
