# Generated by Django 5.0.1 on 2024-01-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0003_test_cast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='cast',
            field=models.JSONField(null=True),
        ),
    ]
