# Generated by Django 5.0.1 on 2024-01-19 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0004_alter_test_cast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='cast',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='review_score',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
