# Generated by Django 5.0.1 on 2024-01-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0005_alter_test_cast_alter_test_duration_alter_test_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='cast',
            field=models.CharField(blank=True, null=True),
        ),
    ]
