# Generated by Django 5.0.1 on 2024-01-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0007_alter_test_country_alter_test_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='release_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
