# Generated by Django 5.0.1 on 2024-01-20 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0008_alter_test_release_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
